/**
 * App-layer tests for the scan page's verdict logic.
 *
 * Runs under `node --test` (not vitest) per D17: contract tests exercise
 * compiled circuits on vitest; the app layer stays on the platform runner.
 *
 * The fixture is NOT hand-written state: it is `site/verify/demo-data.json`,
 * generated by running the real compiled circuits (scripts/export-demo-state).
 * So when these tests assert "vehicle B's write-off question is not-proven",
 * they are asserting what the actual contract actually left on the ledger.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { passportView, formatBound, formatNumber, QUESTIONS } from '../../site/assets/verdict.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ledger = JSON.parse(readFileSync(join(ROOT, 'site', 'verify', 'demo-data.json'), 'utf8'));
const vocabulary = JSON.parse(readFileSync(join(ROOT, 'site', 'verify', 'fields.json'), 'utf8'));

const [A, B] = vocabulary.demoVehicles.map((v) => v.vinHash);
const answers = (vin) => {
    const view = passportView(ledger, vin, vocabulary);
    assert.equal(view.found, true);
    return Object.fromEntries(view.answers.map((a) => [a.field, a]));
};

// ---------------------------------------------------------------- vehicle A

test('vehicle A: every buyer question is proven against the current record', () => {
    const a = answers(A);
    for (const q of QUESTIONS) {
        assert.equal(a[q.field].status, 'proven', `${q.field} should be proven`);
    }
});

test('vehicle A: the mileage verdict carries its public bound, never a reading', () => {
    const a = answers(A);
    assert.equal(a.odometerKm.claim.bound, '150000');
    // The reading (83 260 km) exists only in the generating process. If it
    // were anywhere in the exported ledger, the demo would be a lie.
    assert.ok(!JSON.stringify(ledger).includes('83260'));
});

// ---------------------------------------------------------------- vehicle B

test('vehicle B: unproven questions are not-proven — never inferred as a no', () => {
    const b = answers(B);
    assert.equal(b.writeOffCategory.status, 'not-proven');
    assert.equal(b.accidentCount.status, 'not-proven');
    assert.equal(b.ownerCount.status, 'not-proven');
    // ...while the claim it DID prove renders as proven.
    assert.equal(b.odometerKm.status, 'proven');
    assert.equal(b.odometerKm.claim.bound, '200000');
});

test('vehicle B: a not-proven question carries no claim to mis-render', () => {
    const b = answers(B);
    assert.equal(b.writeOffCategory.claim, null);
});

// ---------------------------------------------------------------- supersession

test('a claim stops being current when the field moves on', () => {
    // Simulate the on-chain future: vehicle A gets a new odometer commitment.
    // The claim row is untouched — exactly what a verifier would face.
    const later = structuredClone(ledger);
    const odoClaim = later.claims.find(
        (c) => c.vinHash === A && c.bound === '150000'
    );
    later.fieldCommitment[odoClaim.slot] = 'f'.repeat(64);

    const view = passportView(later, A, vocabulary);
    const odo = view.answers.find((a) => a.field === 'odometerKm');
    assert.equal(odo.status, 'superseded');
    // The other claims still verify against their untouched commitments.
    assert.equal(view.answers.find((a) => a.field === 'writeOffCategory').status, 'proven');
});

test('among several claims, a current one beats a superseded one', () => {
    const later = structuredClone(ledger);
    const odoClaim = later.claims.find((c) => c.vinHash === A && c.bound === '150000');
    // A second, looser claim proven against the NEW commitment.
    const fresh = { ...odoClaim, key: '1'.repeat(64), bound: '160000', commitment: 'f'.repeat(64) };
    later.claims.push(fresh);
    later.fieldCommitment[odoClaim.slot] = 'f'.repeat(64);

    const odo = passportView(later, A, vocabulary).answers.find((a) => a.field === 'odometerKm');
    assert.equal(odo.status, 'proven');
    assert.equal(odo.claim.bound, '160000');
});

// ---------------------------------------------------------------- edges

test('an unknown VIN hash is not found, not an empty passport', () => {
    assert.equal(passportView(ledger, 'a'.repeat(64), vocabulary).found, false);
});

test('a claim outside the standard questions still surfaces as an extra', () => {
    // Nothing may sit on the ledger that the page silently hides. Today the
    // standard questions cover every demo claim; prove the fallback works by
    // adding a floor claim, which no standard question matches.
    const later = structuredClone(ledger);
    const base = later.claims.find((c) => c.vinHash === A);
    later.claims.push({ ...base, key: '2'.repeat(64), atMost: false, bound: '1' });

    const view = passportView(later, A, vocabulary);
    assert.equal(view.extras.length, 1);
    assert.equal(view.extras[0].claim.atMost, false);
});

test('every ledger claim is either an answer or an extra — none vanish', () => {
    for (const vin of [A, B]) {
        const view = passportView(ledger, vin, vocabulary);
        const shown =
            view.answers.filter((a) => a.claim).length + view.extras.length;
        assert.equal(shown, view.claimCount);
    }
});

// ---------------------------------------------------------------- formatting

test('bounds format for humans without changing the number', () => {
    // The separator is U+202F, narrow no-break space, so a bound never wraps
    // mid-number on a phone. Asserted by escape on purpose: a lookalike plain
    // space in this file cost a debugging round once already.
    assert.equal(formatBound('km', '150000'), '150 000 km');
    assert.equal(formatBound('count', '0'), '0');
    assert.equal(formatNumber('1234567'), '1 234 567');
});
