/**
 * Scan page wiring: URL -> ledger source -> verdict view -> DOM.
 *
 * All judgement lives in verdict.mjs, which node --test exercises against
 * ledger state generated by the real compiled circuits; this file only
 * renders what that module decides. If a verdict looks wrong, the fix is
 * there, under test: never here.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
import { passportView, formatBound, formatNumber } from './verdict.mjs';
import { loadState } from './sources.mjs';

const app = document.getElementById('app');
const badge = document.getElementById('src-badge');
const params = new URLSearchParams(location.search);

const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
};
const short = (hex) => `${hex.slice(0, 10)}…${hex.slice(-6)}`;

// ---------------------------------------------------------------- states

function showError(title, message) {
    app.replaceChildren();
    const box = el('div', 'notice err');
    box.append(el('h2', null, title), el('p', null, message));
    app.append(box);
}

function showLanding(vocabulary) {
    app.replaceChildren();
    const wrap = el('div', 'landing');
    wrap.append(
        el('h1', null, 'Check a vehicle'),
        el('p', null,
            'Scan the QR code on a vehicle or its listing and this page opens on its passport. ' +
            'Nothing here yet: or try a demonstration vehicle:')
    );
    for (const v of vocabulary.demoVehicles ?? []) {
        const btn = el('button', 'vehicle-pick');
        btn.type = 'button';
        const b = el('b', null, v.title);
        const s = el('span', null, v.blurb);
        btn.append(b, s);
        btn.addEventListener('click', () => {
            params.set('v', v.vinHash);
            location.search = params.toString();
        });
        wrap.append(btn);
    }
    app.append(wrap);
}

// ---------------------------------------------------------------- verdicts

const STATUS_TEXT = {
    proven: { glyph: '✓', sub: 'Proven against the current record' },
    superseded: {
        glyph: '⚠',
        sub: 'Proven against an earlier version, ask for a fresh proof'
    },
    'not-proven': { glyph: '—', sub: 'No claim on the ledger. Not a no: not proven.' }
};

function verdictCard(label, status, claim, meta) {
    const card = el('details', `verdict v-${status}`);
    const head = el('summary');
    head.append(el('span', 'badge', STATUS_TEXT[status].glyph));

    const lab = el('span', 'v-label');
    lab.append(el('b', null, label), el('small', null, STATUS_TEXT[status].sub));
    head.append(lab, el('span', 'chev', '▶'));
    card.append(head);

    const detail = el('div', 'v-detail');
    if (claim) {
        detail.append(el('p', null,
            'A zero-knowledge proof was accepted on the ledger for this claim. It could not have ' +
            'been produced unless the hidden value satisfied the bound: and the value itself ' +
            'was never published.'));
        const dl = el('dl');
        const row = (dt, dd) => { dl.append(el('dt', null, dt), el('dd', null, dd)); };
        row('claim', `${meta?.label ?? claim.fieldKey.slice(0, 12)} ${claim.atMost ? '≤' : '≥'} ${formatBound(meta?.kind, claim.bound)}`);
        row('field key', short(claim.fieldKey));
        row('proven against', short(claim.commitment));
        row('ledger slot', short(claim.slot));
        detail.append(dl);
        if (status === 'superseded') {
            detail.append(el('p', null,
                'The field has been updated since this proof was made, so it describes an earlier ' +
                'version of the record. The claim was true then; a current proof would need to be ' +
                'made again.'));
        }
    } else {
        detail.append(el('p', null,
            'Nothing on the ledger answers this question. A failed proof writes nothing, and no ' +
            'proof was recorded: so the honest rendering is “not proven”, never a ' +
            'quiet “no”. Ask the seller for the proof; if the claim is true of the ' +
            'record, producing it costs one transaction.'));
    }
    card.append(detail);
    return card;
}

function showPassport(view, vinHex) {
    app.replaceChildren();

    const head = el('div', 'passport-head');
    head.append(el('h1', null, 'Vehicle passport'));
    head.append(el('span', 'hash', `VIN hash ${vinHex}`));
    app.append(head);

    for (const a of view.answers) {
        let label = a.label;
        if (a.field === 'odometerKm' && a.claim) {
            label = `Mileage under ${formatBound('km', a.claim.bound)}`;
        }
        app.append(verdictCard(label, a.status, a.claim, a.meta ?? null));
    }

    for (const x of view.extras) {
        const dir = x.claim.atMost ? 'at most' : 'at least';
        const label = `${x.meta?.label ?? 'Field'} ${dir} ${formatBound(x.meta?.kind, x.claim.bound)}`;
        app.append(verdictCard(label, x.status, x.claim, x.meta));
    }

    const reg = el('p', 'registrar-line');
    reg.append('Registered by ');
    const code = el('code', null, short(view.registrar));
    reg.append(code, ` · ${formatNumber(view.claimCount)} claim${view.claimCount === 1 ? '' : 's'} on the ledger`);
    app.append(reg);
}

// ---------------------------------------------------------------- boot

(async () => {
    let data;
    try {
        data = await loadState('', params);
    } catch (e) {
        showError('Could not read the ledger', e.message);
        return;
    }
    badge.textContent = data.badge;
    badge.hidden = false;

    const vin = params.get('v');
    if (!vin) {
        showLanding(data.vocabulary);
        return;
    }
    const view = passportView(data.ledger, vin.toLowerCase(), data.vocabulary);
    if (!view.found) {
        showError('No passport for this code',
            'The ledger holds no passport under this VIN hash. Either the code is not a ' +
            'ShieldVIN code, or this vehicle was never registered.');
        return;
    }
    showPassport(view, vin.toLowerCase());
})();
