/**
 * Where the scan page gets ledger state — behind one interface, so the answer
 * to "can a plain browser page read preprod directly?" changes a source, not
 * the page. Same shape as D12's signing interface, for the same reason.
 *
 *   demo  ledger state exported from the real compiled circuits by
 *         scripts/export-demo-state.mjs. Honest about what it is: the page
 *         labels it, and the JSON itself names its generator.
 *
 *   live  the deployed contract on Midnight preprod. Not wired yet — reading
 *         contract state from a no-build-step page is an open question with
 *         ODATANO (keyless reads exist in @odatano/nightgate-tx, but that is
 *         a Node SDK). Until answered, this source says so instead of
 *         pretending.
 *
 * A source resolves to `{ ledger, vocabulary, badge }` or throws with a
 * message fit to show a person.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

const fetchJson = async (url) => {
    const r = await fetch(url, { cache: 'no-store' });
    if (!r.ok) throw new Error(`could not load ${url} (${r.status})`);
    return r.json();
};

export const SOURCES = {
    demo: {
        badge: 'demo ledger — generated by the compiled contract, not read from chain',
        async load() {
            const [ledger, vocabulary] = await Promise.all([
                fetchJson('./demo-data.json'),
                fetchJson('./fields.json')
            ]);
            return { ledger, vocabulary, badge: this.badge };
        }
    },

    live: {
        badge: 'live — Midnight preprod',
        async load() {
            throw new Error(
                'The live read is not wired yet: the contract is not deployed to preprod, ' +
                'and the browser read path is being confirmed with ODATANO. ' +
                'Use ?src=demo meanwhile.'
            );
        }
    }
};

export function pickSource(params) {
    const name = params.get('src') ?? 'demo';
    return SOURCES[name] ?? SOURCES.demo;
}
