/**
 * Verdict logic for the scan page: pure functions over exported ledger JSON.
 *
 * Kept framework-free and DOM-free on purpose: the page imports this as an ES
 * module, and `test/app/scan-verdict.test.mjs` runs the same file under
 * `node --test` against ledger state generated by the real compiled circuits.
 * If the page and the tests disagreed about what a claim means, one of them
 * would be lying; sharing this module is what prevents that.
 *
 * The one rule that matters here: a verdict comes FROM A CLAIM ON THE LEDGER
 * or it does not exist. This module never infers "clean" from silence: a
 * question with no claim behind it is `not-proven`, rendered as exactly that.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * The questions a buyer actually asks, in the order they ask them.
 * `bound` is the strictest bound that still answers the question; a claim
 * with a LOWER-or-equal bound in the same direction also answers it.
 * `bound: null` accepts any at-most claim on the field (a ceiling is the
 * answer; its size is shown rather than judged).
 */
export const QUESTIONS = [
    { field: 'writeOffCategory', atMost: true, bound: 0n, label: 'Never written off' },
    { field: 'accidentCount', atMost: true, bound: 0n, label: 'No reported accidents' },
    { field: 'ownerCount', atMost: true, bound: 1n, label: 'One keeper from new' },
    { field: 'odometerKm', atMost: true, bound: null, label: 'Mileage under a stated ceiling' }
];

/** "150000" -> "150 000": thin-space grouping, no locale surprises. */
export const formatNumber = (s) =>
    String(s).replace(/\B(?=(\d{3})+(?!\d))/g, ' ');

export const formatBound = (kind, bound) => {
    const n = formatNumber(bound);
    if (kind === 'km') return `${n} km`;
    return n;
};

/**
 * Everything the page needs to render one vehicle, derived from the exported
 * ledger and the public field vocabulary.
 *
 * Statuses per question:
 *   'proven'      a claim answers it, made against the field's CURRENT value
 *   'superseded'  a claim answers it, but the field has moved on since: the
 *                 claim was true of an earlier version, ask for a fresh proof
 *   'not-proven'  no claim on the ledger answers it; this is NOT "no"
 */
export function passportView(ledger, vinHex, vocabulary) {
    const contentRoot = ledger.passports[vinHex];
    if (!contentRoot) return { found: false };

    const byKey = vocabulary.fields;
    const nameToKey = Object.fromEntries(
        Object.entries(byKey).map(([k, meta]) => [meta.name, k])
    );

    const mine = ledger.claims.filter((c) => c.vinHash === vinHex);
    const isCurrent = (c) => ledger.fieldCommitment[c.slot] === c.commitment;

    const answers = QUESTIONS.map((q) => {
        const keyHex = nameToKey[q.field];
        const candidates = mine.filter(
            (c) =>
                c.fieldKey === keyHex &&
                c.atMost === q.atMost &&
                (q.bound === null || BigInt(c.bound) <= q.bound)
        );
        if (candidates.length === 0) {
            return { ...q, status: 'not-proven', claim: null };
        }
        // Prefer a claim about the current value; among those, the tightest.
        const ranked = [...candidates].sort((a, b) => {
            const cur = Number(isCurrent(b)) - Number(isCurrent(a));
            if (cur !== 0) return cur;
            return BigInt(a.bound) < BigInt(b.bound) ? -1 : 1;
        });
        const best = ranked[0];
        return {
            ...q,
            status: isCurrent(best) ? 'proven' : 'superseded',
            claim: best,
            meta: byKey[best.fieldKey] ?? null
        };
    });

    // Claims that answered no standard question still deserve a row: a
    // verifier should never discover ledger state the page chose not to show.
    const shown = new Set(answers.filter((a) => a.claim).map((a) => a.claim.key));
    const extras = mine
        .filter((c) => !shown.has(c.key))
        .map((c) => ({
            claim: c,
            meta: byKey[c.fieldKey] ?? null,
            status: isCurrent(c) ? 'proven' : 'superseded'
        }));

    return {
        found: true,
        contentRoot,
        registrar: ledger.registrar[vinHex] ?? null,
        answers,
        extras,
        claimCount: mine.length
    };
}
